title = "Discord Bridge"
gitSourceBranch = "master"
tagline = "Discord webhooks made easy!"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
[docusarus.themeConfig.prism]
additionalLangues = ["lua", "luau", "cpp"]

[[classOrder]]
section = "Hooks"
classes = ["Hook"]

[[classOrder]]
section = "Message"
classes = ["Message", "EmbedFields"]

[footer]
style = "dark"
copyright = "Copyright © 2025 Void Labs Development. Built with Moonwave and Docusaurus"